name: MSBuild and Release

on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  buld:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        
      - run: dotnet build --configuration Release
      #- run: dotnet test
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.event.pull_request.title}}
          release_name: ${{github.event.pull_request.title}}
          body: ${{github.event.pull_request.body}}
          draft: false
          prerelease: false
      - name: Upload release asset # https://github.com/actions/upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{secretes.GIHTUB_TOKEN}}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: PickPicTweet/bin/Release/net6.0/PickPicTweet.exe
          asset_name: PickPicTweet.exe
          asset_content_type: application/octet-stream
        
